### ISSUE TITLE
Undefined when number of files > fileMaxCount 

### ISSUE THREAD

**Issue by versusvoid** [vugar005/ngx-awesome-uploader#10]
Got an undefined at https://github.com/vugar005/ngx-awesome-uploader/blob/e0f124aee00ff613851b8b86a36f479887c0a2e9/projects/file-picker/src/lib/file-picker.component.ts#L178
when uploading second file after previous successful upload. Max file count check failed due `this.files` still referencing previous file, and argument referencing new file.
`handleFiles()` then returns `undefined`

8.0.2

**Comment by vugar005** [comment]
Hi @versusvoid 
Thank you for feedback. The problem is solved from version 8.0.3.
