### ISSUE TITLE
import error from non ecmascript

### ISSUE THREAD

**Issue by mp051998** [vugar005/ngx-awesome-uploader#102]
I get this error while importing the FilePickerModule.
Any idea how to handle it properly?

```
Error: ./node_modules/ngx-awesome-uploader/fesm2015/ngx-awesome-uploader.mjs 374:4-25
Can't import the named export 'ɵɵtextInterpolate1' from non EcmaScript module (only default export is available)
```

**Comment by vugar005** [comment]
Hi which version of Angular are you using and which version of library?

**Comment by mp051998** [comment]
angular version 11.2.8 and library 13.0.0

**Comment by vugar005** [comment]
Library version 13 is using ESM module. You should either use v11 or v12 of library. @mp051998

**Comment by mp051998** [comment]
> Library version 13 is using ESM module. You should either use v11 or v12 of library. @mp051998 

Ah, I'll try that. Thanks!!
