### ISSUE TITLE
Demo not working?

### ISSUE THREAD

**Issue by teichsta** [vugar005/ngx-awesome-uploader#116]
Hi,

stumbled upon this component which reads great … tried to execute the demo on stackblitz which unfortunately doesn't work properly (it simply doesn't start).

Any idea what am i doing wrong?

 Best, Thomas

**Comment by teichsta** [comment]
any idea @vugar005 ?

**Comment by vugar005** [comment]
Hi @teichsta 
I tested and it works.
![image](https://github.com/vugar005/ngx-awesome-uploader/assets/28726265/6b540998-3893-4fb0-899b-c32051823a90)
Demo link:  https://stackblitz.com/edit/ngx-awesome-uploader?file=src%2Fapp%2Fsimple-demo%2Fsimple-demo.component.ts
Can you try to remove cache of stackblitz and try again?

**Comment by teichsta** [comment]
i removed the cache completely and now it works also on my side! Thanks a lot and sorry for bothering!

**Comment by vugar005** [comment]
no problem.
