### ISSUE TITLE
FR: Api to change color

### ISSUE THREAD

**Issue by Ruud-cb** [vugar005/ngx-awesome-uploader#18]
Hi,

I think the default design for the dropzone and button is just fine, no need to customize that. The only thing I would want to change is the color to the theme color of my angular application.

Would be great if you could add that, saves time on rebuilding the nice cloud icon  and such.

**Comment by vugar005** [comment]
Hi, thanks for issue. @Ruud-cb, you can either use custom dropzon or just custom classes which will override the default color scheme. Closing this issue.
