### ISSUE TITLE
EventEmmiter upload not working

### ISSUE THREAD

**Issue by LucasLopesr** [vugar005/ngx-awesome-uploader#20]
(uploadSuccess) eventemitter not launching when a file is uploaded

`      <ngx-file-picker #uploader 
          [adapter]="adapter" 
          [uploadType]="'single'"  
          [fileMaxCount]='1'
          [showeDragDropZone]="true" 
          [showPreviewContainer]="true" 
          [itemTemplate]="template" 
          [fileExtensions]="['pdf', 'txt', 'docx', 'doc']"
          (validationError)="onValidationError($event)" 
          (uploadSuccess)="onUploadSuccess($event)"
          (removeSuccess)="onRemoveSuccess($event)" 
          (fileAdded)="onFileAdded($event)">
`

on Component.ts
`  onUploadSuccess(e: FilePreviewModel) {
   console.log('uploadSuccess');
  }`

The other methods work normally.
Does anyone know the reason?

**Comment by vugar005** [comment]
Hi @LucasLopesr 
In adapter / uploadFile method, do you return string type if  response is HttpEventType.Response ?
checkout: [demo adapter](https://github.com/vugar005/ngx-awesome-uploader/blob/master/projects/file-picker/src/lib/mock-file-picker.adapter.ts)

**Comment by vugar005** [comment]
The issue is fixed from version 9.0.1

**Comment by riamchandani** [comment]
Its not working for me, I have the latest version but the emitter doesn't work
