### ISSUE TITLE
picker.service.ts type: 'UploadProgreess' bug

### ISSUE THREAD

**Issue by evolmk** [vugar005/ngx-awesome-uploader#22]
**Nice project!**  I'm not sure what this impacts, but saw this:

**Incorrect Spelling:** `UploadProgreess`

https://github.com/vugar005/ngx-awesome-uploader/blob/master/projects/file-picker/src/lib/file-picker.service.ts#L11
```
detail: {
        type: 'UploadProgreess'
      }
```

**Comment by vugar005** [comment]
Hi @evolmk .
Thanks for detail) It is only used in unit test and does not affect library functionality.
Kind Regards
