### ISSUE TITLE
No way to handle upload errors when using custom templates

### ISSUE THREAD

**Issue by wojryba** [vugar005/ngx-awesome-uploader#25]
Hi
there seems to currently be no way to show that some kind of error happened during file upload when using custom templates.

**Comment by vugar005** [comment]
@wojryba  Thanks for report. The issue is fixed from version 9.0.1

**Comment by wojryba** [comment]
@vugar005 I tried the new version and the only thing that I see that changed is that for some reason horizontal scroll appeared in my custom template. I looked into the code of the last commit and I don't really see how can it help us handle errors in custom templates.
I also don't see any changes to the docs.

Could you please explain/show how the upload errors should be handled in custom templates?

**Comment by vugar005** [comment]
@wojryba . You mean upload errors? Yes thanks. I added support for upload fail. You can see on documentation uploadFail event will be emitted when there is api error. Available form version 9.0.4
