### ISSUE TITLE
Cropper transparency change background color

### ISSUE THREAD

**Issue by karaagacylmaz** [vugar005/ngx-awesome-uploader#30]
How can i change cropped image background color.

i tried send "fillColor" parameter with cropperOptions, but didn't work. 

Default uploaded image:
![175929_da7553e7-6810-4dd6-b6a1-406c3a22d51f](https://user-images.githubusercontent.com/37292831/77652073-bfa44e00-6f7e-11ea-8182-09fe7b2c5ea4.jpg)

top and bottom is black. 
i wanna change this color with white

**Comment by karaagacylmaz** [comment]
@vugar005

**Comment by vugar005** [comment]
Hi @karaagacylmaz . I think you can change the style with just css. I dont think it is needed to add that feature.

**Comment by BerezinViktor** [comment]
@vugar005 But it's not about css style, it's about result image, it can't be changed by css. Just load the png image and crop it by your library. You will see that the background will be black for transparent areas. @karaagacylmaz meant to change the default bg color to white. Maybe it should be moved to cropperjs.
