### ISSUE TITLE
Additional parameter for deleting

### ISSUE THREAD

**Issue by wolejnik** [vugar005/ngx-awesome-uploader#31]
Hi,
after calling out the method `uploadFile`, in API saved image and return **idImg**.

How to call the `removeFile `method from the html template view where it will pass the **idImg** parameter ?

Can you help me ? @vugar005

**Comment by vugar005** [comment]
hi @wolejnik . The FilePicker component has public method called
 ` removeFile(fileItem: FilePreviewModel)`
In ts file, access this filePickerComponent (via ViewChild) and call this method.

**Comment by vugar005** [comment]
[Example](https://stackblitz.com/edit/ngx-awesome-uploader?file=src%2Fapp%2Fadvanced-demo%2Fadvanced-demo.component.ts) how you access the component:

**Comment by vugar005** [comment]
.
