### ISSUE TITLE
Edit mode support without file Object

### ISSUE THREAD

**Issue by kamlesh0606** [vugar005/ngx-awesome-uploader#33]
Hi,

Edit mode support need without file Object in FilePreviewModel.

```
@ViewChild('uploader') uploader: FilePickerComponent;
this.uploader.files = [{file : null , fileName : "sdfdsf.pdf" , fileId : "sdsadsa.pdf"}];
```

**Comment by vugar005** [comment]
@kamlesh0606  fixed from version [10.0.0](https://github.com/vugar005/ngx-awesome-uploader/releases/tag/10.0.0)
