### ISSUE TITLE
Feeding data for a continuous experience

### ISSUE THREAD

**Issue by lkowalski-smartbusiness** [vugar005/ngx-awesome-uploader#37]
Hi @vugar005, where would I have to start if one of my requirements is providing the list of previously uploaded files? Is there a way to feed an array of files to the FileComponent on init?
The preview mode would probably fail at that point but it's not an issue for now

**Comment by vugar005** [comment]
@lkowalski-smartbusiness  Hi Thanks for feedback. Yes I see it is a nice to have feature which can be used. I am going to add this to backlog and let you know after new release.

**Comment by vugar005** [comment]
Closing as it is already avialable from version 10. Thanks.
