### ISSUE TITLE
How to programatically clear all files after calling an API

### ISSUE THREAD

**Issue by ria-designway** [vugar005/ngx-awesome-uploader#39]
Hi,

I have a form which consists of a file uploader, a few input fields and a submit button, after uploading the files and filling the other details, the user clicks submit, which makes an API, if I receive a 200 status, I need to clear the ngx file data and the preview, which is still visible, how do I clear it?

Languages and Framework:
Typescript, angular 9.

**Comment by vugar005** [comment]
@ria-designway  Hi you can do that by getting component and assigning its files to empty array. So files will be removed. You can find in advanced demo , how to access component api. Let me know if it fixed your issue.

**Comment by ria-designway** [comment]
Hi @vugar005 , thank you for your response, it did work to some extent, i.e, that file array becomes empty, but it is still displayed in the preview container.

HTML :

  ```
<ngx-file-picker id="fileDrop" [totalMaxSize]="10" [fileMaxCount]="5" [fileMaxSize]="5"
 [uploadType]="'multi'" (validationError)="onValidationError($event)"  [adapter]="filesData.fileAccordion[idx].adapter" [fileExtensions]="['pdf', 'jpg', 'jpeg', 'png']" [enableCropper]="false" (uploadSuccess)="onUploadSuccess($event)"  
(removeSuccess)="onRemoveSuccess($event)" [showeDragDropZone]="true" [showPreviewContainer]="true"  (fileAdded)="onFileAdded($event)">

   <div class="dropzoneTemplate">
        <div class="upload-box >
              <label class="upload-box__lable" for="fileUpload">
                  <span class="upload-box__lable-icon"><img src="assets/images/upload-icon.svg" alt=""></span>
                  <span class="upload-box__lable--bluetext">Choose File(s)</span> or drag here to upload
             </label>
      </div>
   </div>
</ngx-file-picker>
```

TypeScript:
```
 createAccodionData(data) {
    for (let val of data) {
      this.filesData.fileAccordion.push({
        fileUploadStatus: "notSubmitted",
        adapter: new DemoFilePickerAdapter(this.http)
      })
    }
  }

SubmitFile(idx){
   this.filesData.fileAccordion[idx].fileUploadStatus = "submitted";
        this.filesData.fileAccordion[idx].adapter = new DemoFilePickerAdapter(this.http);
}
```

Is there something else that I'm missing here?

**Comment by O-mkar** [comment]
Here is a how you remove multiple childs

**HTML**
`<ngx-file-picker  #upload> </ngx-file-picker  #upload>   // 👈🏻add a referance to for your child componend`

**TS FILE**

```
  @ViewChildren('uploader') uploaders: QueryList<FilePickerAdapter>;  // Declare ViewChildren

SubmitFile(idx){
  for (const item of this.filesData.fileAccordion[idx].adapter.files) {
        this.uploaders.toArray()[idx].removeFile(item)
      
      }
}

```

**Comment by vugar005** [comment]
@O-mkar  Thanks. Closed.
