### ISSUE TITLE
How to access the file data?

### ISSUE THREAD

**Issue by andrebrz** [vugar005/ngx-awesome-uploader#41]
Hello,

How could I access the data of the file I uploaded? I'm asking this because I want to show the image in the html file, using something like this:
`<img src="myFiles[0].data">`

For example, when I add a file, inside the method onFileAdded If I do a console.log(file) I don't find the "data" which would be the content of the image:

` onFileAdded(file: FilePreviewModel) {
    console.log(file);
    this.myFiles.push(file);
  }`

**Comment by vugar005** [comment]
@andrebrz  Hi. The content should be file field inside file.

**Comment by vugar005** [comment]
@andrebrz  Now you can access BE data after file upload. FIlePickerAdapter is improved from version [10.0.0](https://github.com/vugar005/ngx-awesome-uploader/releases/tag/10.0.0)
