### ISSUE TITLE
how can I change file-preview-item style

### ISSUE THREAD

**Issue by dpmert** [vugar005/ngx-awesome-uploader#49]
[_nghost-c22] {
    display: block;
    padding: 20px 16px;
    border-bottom: 1px solid #ebeef1;
    max-width: 440px;  /* I want change ' none' */
    position: relative;
}

and

I want to manipulate the installation successful, reload, install failed icons

**Comment by vugar005** [comment]
Hi. You can change the style globally by :ng-deep
