### ISSUE TITLE
PNG transparent area changed to black 

### ISSUE THREAD

**Issue by avialonn** [vugar005/ngx-awesome-uploader#50]
Hi,
When cropping an image the transparent area goes to black.
Any idea on how to fix it?
Thanks

**Comment by BerezinViktor** [comment]
Created pull request for fix this issue.
https://github.com/vugar005/ngx-awesome-uploader/pull/52

**Comment by vugar005** [comment]
@avialonn  Fixed from 9.0.9 version. Thanks @BerezinViktor  for contribution.
