### ISSUE TITLE
How to catch errors in remove file Api

### ISSUE THREAD

**Issue by tanveer21** [vugar005/ngx-awesome-uploader#51]
If upload file API fails we have uploadFail event. Similarly, do we have any method for removeFail?

I am using a file picker adapter. it works fine for all cases just stuck with this. can anyone help?

**Comment by vugar005** [comment]
Well can you tell please which error you receive on removeFail because basically it just removes file from files list.

**Comment by tanveer21** [comment]
Actually i have scenario where the image got deleted from the google storage so i get a 404 response from the remove api call. 
And in that case i am unable to handle the failed use case on UI.


// adapter remove function i am using
public removeFile(fileItem): Observable<any> {
        this.loader.showLoader();
        const body = { imageId: fileItem.fileId};
        return this.http.post(this.removeUploadUrl, body);
    }

**Comment by tanveer21** [comment]
Any help on this?

**Comment by vugar005** [comment]
@tanveer21 file adapter changed. Checkout new  from version [10.0.0](https://github.com/vugar005/ngx-awesome-uploader/releases/tag/10.0.0)
