### ISSUE TITLE
UploadFail not firing

### ISSUE THREAD

**Issue by romain-supinski** [vugar005/ngx-awesome-uploader#53]
Hi,
The uploadFail eventEmitter in file-picker never fire. I Think the reason is because it listen to uploadSucces but not to uploadFail. 

```xml 
<file-preview-container
  *ngIf="files"
  [previewFiles]="files"
  (removeFile)="removeFile($event)"
  (uploadSuccess)="onUploadSuccess($event)"
  [adapter]="adapter"
  [itemTemplate]="itemTemplate"
  [captions]="_captions"
  [enableAutoUpload]="enableAutoUpload"
>
```

Is it possible to fix this?
Thanks

ps: it would be great if the observable could return the filePreview and the httpError

**Comment by vugar005** [comment]
@romain-supinski  fixed from version [10.0.0](https://github.com/vugar005/ngx-awesome-uploader/releases/tag/10.0.0)
