### ISSUE TITLE
Cropper buttons labels and trigger

### ISSUE THREAD

**Issue by MoiseScalzo** [vugar005/ngx-awesome-uploader#6]
There is any chance to change (localize) the Crop and Cancel cropper buttons label?
Moreover, the two buttons are not with type="button" attribute, so, if you put the component inside a form, they trigger the submit.

Can you add this fix or, can you provide a way to fix?

thank you in advance.
Moise

**Comment by vugar005** [comment]
Thanks for feedback. Localization support will be added in next release.

**Comment by vugar005** [comment]
@MoiseScalzo Multi Language support added from v8.0.2.
