### ISSUE TITLE
Cropper is changing extension

### ISSUE THREAD

**Issue by pioneer09** [vugar005/ngx-awesome-uploader#73]
Hi.

After the image cropping is done, it says that Image size is too large. This is happening because of image format conversion: jpg -> png.

I found that it is needed to include this line of code but I didn't find any place where to put, in any listener?
 _cropper.getCroppedCanvas().toDataURL('image/jpeg')_

**Comment by vugar005** [comment]
Fixed by PR @Nesci28.
