### ISSUE TITLE
How to assign 'capture' attribute

### ISSUE THREAD

**Issue by jrujano** [vugar005/ngx-awesome-uploader#81]
How to assign 'capture' attribute

I have a development implemented the library but I want to apply the attribute
capture = "camera"

**simulate this result**

'''
```` 

<input type="file" accept="image/*" capture="camera">
````

**Comment by vugar005** [comment]
Hi @jrujano,
This attribute was added now from version 12.0.3.  
You can specify via `[fileInputCapture]="'camera'"`
Docs updated
Thank you!

**Comment by jrujano** [comment]
> 

Thank's
