### ISSUE TITLE
@Input accept parameter doesn't work

### ISSUE THREAD

**Issue by swapnilp0x00** [vugar005/ngx-awesome-uploader#9]
I tried passing `[accept]="'image/*'"` to component input.
But it doesn't work.

On HTML input tag it works fine.
`<input type="file" accept="image/*">`

**Comment by vugar005** [comment]
Thank u for info. Fixed from version 8.0.1.

**Comment by swapnilp0x00** [comment]
Updated and tested.
It is working now. 
Thanks a ton @vugar005 .

**Comment by vugar005** [comment]
@swapnilp0x00 Thank you for confirming. Welcome)
