### ISSUE TITLE
Cropbox is too small

### ISSUE THREAD

**Issue by Ruud-cb** [vugar005/ngx-awesome-uploader#95]
Simply open the stackplitz [demo](https://stackblitz.com/edit/ngx-awesome-uploader?file=src%2Fapp%2Fadvanced-demo%2Fadvanced-demo.component.html) (which is referenced in the Docs) and see that the cropbox is very small after uploading:

<img width="522" alt="image" src="https://user-images.githubusercontent.com/10037514/154665285-51edb9ec-f23f-43c2-aa92-2bfba2e76300.png">

This example image is 1584x1056 pixels.

I've also tried to use `cropperOptions` and look at the [docs of cropperJS](https://github.com/fengyuanchen/cropperjs/blob/main/README.md#mincontainerwidth), that seems to help but I have to manually calculate what screen dimensions I need.

**Comment by vugar005** [comment]
Hi @Ruud-cb, unfortunately this is related to cropperJs. There nothing should this package can do. At lease it should not. I would suggest using fix height and width by providing cropper options.
